# swagger.yaml
openapi: 3.0.0
info:
  title: Strady API
  description: API for the Strady Financial Tracker application.
  version: 1.0.0
servers:
  - url: /

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Transaction:
      type: object
      properties:
        _id:
          type: string
          example: 63a5e3f1a9b2c...
        userId:
          type: string
          example: user_12345
        assetSymbol:
          type: string
          example: AAPL
        # ... define all other fields from your Transaction model

security:
  - bearerAuth: []

paths:
  /api/transactions:
    get:
      summary: Get all transactions for the logged-in user
      tags: [Transactions]
      security:
        - bearerAuth: [] # This endpoint requires a token
      responses:
        '200':
          description: A list of transactions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '401':
          description: Unauthorized